package com.anc.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import lombok.Data;

@Data
public class AncVisitRequestDTO {

    @JsonProperty("patientId")
    private String patientId;

    @JsonProperty("patientName")
    private String patientName;

    @JsonProperty("workerId")
    private String workerId;

    @JsonProperty("phcId")
    private String phcId;

    // Optional — auto-generated by ClinicalSummaryBuilder if not sent
    @JsonProperty("clinical_summary")
    private String clinicalSummary;

    @Valid
    @NotNull(message = "Structured data is required")
    @JsonProperty("structured_data")
    private StructuredDataDTO structuredData;
}
